# permissions for end users to edit rscts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rsct-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rsct-operator
    app.kubernetes.io/part-of: rsct-operator
    app.kubernetes.io/managed-by: kustomize
  name: rsct-editor-role
rules:
- apiGroups:
  - rsct.ibm.com
  resources:
  - rscts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rsct.ibm.com
  resources:
  - rscts/status
  verbs:
  - get
