# permissions for end users to view rscts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rsct-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rsct-operator
    app.kubernetes.io/part-of: rsct-operator
    app.kubernetes.io/managed-by: kustomize
  name: rsct-viewer-role
rules:
- apiGroups:
  - rsct.ibm.com
  resources:
  - rscts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rsct.ibm.com
  resources:
  - rscts/status
  verbs:
  - get
